Import("env")


def source(file):
    return "#/src/engine/" + file

env["source_files"] += [
    source("app.cpp"),
    source("imw.cpp"),
    source("input.cpp"),
    source("render.cpp")
]

SConscript("#/src/engine/imgui/SConscript", exports="env")