Import("env")


def source(file):
    return "#/src/" + file

env["source_files"] += [
    source("main.cpp")
]

SConscript("#/src/engine/SConscript", exports="env")
SConscript("#/src/game/SConscript", exports="env")
SConscript("#/src/editor/SConscript", exports="env")